#!/usr/bin/env bash
set -euo pipefail

PACKAGE_NAME="gateway-api-envoy"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_VERSION="$(tr -d '[:space:]' < "${ROOT_DIR}/VERSION")"
ENVOY_GATEWAY_VERSION="${DEFAULT_VERSION}"
ARCH="all"
DIST_DIR="${ROOT_DIR}/dist"
BUILD_ROOT="${ROOT_DIR}/.build"
DEFAULT_REGISTRY="sealos.hub:5000/kube4"
CHART_REF="oci://docker.io/envoyproxy/gateway-helm"
USE_LOCAL_ASSETS=0
SKIP_IMAGES=0
KEEP_BUILD=0
ENVOY_PROXY_IMAGE="docker.io/envoyproxy/envoy:distroless-v1.35.0"

usage() {
  cat <<USAGE
Usage: bash build.sh [options]

Build an offline .run package for Gateway API + Envoy Gateway.

Options:
  --arch <amd64|arm64|all>          Target architecture. Default: all.
  --version <version>               Envoy Gateway chart/image version. Default: ${ENVOY_GATEWAY_VERSION}
  --chart-ref <oci-ref>             Helm chart ref. Default: ${CHART_REF}
  --envoy-proxy-image <image>       Envoy Proxy data-plane image. Default: ${ENVOY_PROXY_IMAGE}
  --use-local-assets                Use upstream/gateway-helm-<version>.tgz instead of helm pull.
  --skip-images                     Package chart only; do not pull/save images. For smoke tests only.
  --keep-build                      Keep .build/ working directories after packaging.
  -h, --help                        Show this help.

Expected local chart asset when --use-local-assets is used:
  upstream/gateway-helm-<version>.tgz

The production package contains:
  - Envoy Gateway Helm chart, including Gateway API CRDs and Envoy Gateway CRDs.
  - envoyproxy/gateway controller image.
  - envoyproxy/envoy data-plane image.
  - default GatewayClass + Gateway bootstrap manifests generated by install.sh.
USAGE
}

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo ">>> $*" >&2; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --arch) ARCH="${2:-}"; shift 2 ;;
    --version) ENVOY_GATEWAY_VERSION="${2:-}"; shift 2 ;;
    --chart-ref) CHART_REF="${2:-}"; shift 2 ;;
    --envoy-proxy-image) ENVOY_PROXY_IMAGE="${2:-}"; shift 2 ;;
    --use-local-assets) USE_LOCAL_ASSETS=1; shift ;;
    --skip-images) SKIP_IMAGES=1; shift ;;
    --keep-build) KEEP_BUILD=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ -n "${ENVOY_GATEWAY_VERSION}" ]] || die "version cannot be empty"
case "${ENVOY_GATEWAY_VERSION}" in v*) ;; *) ENVOY_GATEWAY_VERSION="v${ENVOY_GATEWAY_VERSION}" ;; esac
case "${ARCH}" in amd64|arm64|all) ;; *) die "--arch must be amd64, arm64, or all" ;; esac
[[ -n "${ENVOY_PROXY_IMAGE}" ]] || die "--envoy-proxy-image cannot be empty"
ENVOY_PROXY_TARGET="${DEFAULT_REGISTRY}/envoyproxy/${ENVOY_PROXY_IMAGE##*/}"

need tar
need sha256sum
need python3
if [[ "${USE_LOCAL_ASSETS}" != "1" ]]; then
  need helm
fi
if [[ "${SKIP_IMAGES}" != "1" ]]; then
  need docker
fi

[[ -f "${ROOT_DIR}/install.sh" ]] || die "install.sh not found"
[[ -f "${ROOT_DIR}/images/image.json" ]] || die "images/image.json not found"
marker_count="$(grep -cx '__PAYLOAD_BELOW__' "${ROOT_DIR}/install.sh" || true)"
[[ "${marker_count}" == "1" ]] || die "install.sh must contain exactly one standalone __PAYLOAD_BELOW__ marker"
bash -n "${ROOT_DIR}/install.sh"
python3 -m json.tool "${ROOT_DIR}/images/image.json" >/dev/null

arch_list() {
  case "${ARCH}" in
    all) printf '%s\n' amd64 arm64 ;;
    *) printf '%s\n' "${ARCH}" ;;
  esac
}

platform_for_arch() {
  case "$1" in
    amd64) printf '%s\n' linux/amd64 ;;
    arm64) printf '%s\n' linux/arm64 ;;
    *) die "unsupported arch: $1" ;;
  esac
}

chart_asset_name() {
  printf 'gateway-helm-%s.tgz\n' "${ENVOY_GATEWAY_VERSION}"
}

prepare_chart_asset() {
  local cache_dir asset_name asset_path
  cache_dir="${BUILD_ROOT}/chart-${ENVOY_GATEWAY_VERSION}"
  asset_name="$(chart_asset_name)"
  asset_path="${cache_dir}/${asset_name}"
  rm -rf "${cache_dir}"
  mkdir -p "${cache_dir}"

  if [[ "${USE_LOCAL_ASSETS}" == "1" ]]; then
    [[ -f "${ROOT_DIR}/upstream/${asset_name}" ]] || die "missing local asset: upstream/${asset_name}"
    cp "${ROOT_DIR}/upstream/${asset_name}" "${asset_path}"
  else
    info "helm pull ${CHART_REF} --version ${ENVOY_GATEWAY_VERSION}"
    helm pull "${CHART_REF}" --version "${ENVOY_GATEWAY_VERSION}" -d "${cache_dir}" >&2
    [[ -f "${asset_path}" ]] || die "helm pull did not create ${asset_name}"
  fi

  tar -tzf "${asset_path}" >/dev/null
  printf '%s\n' "${asset_path}"
}

write_image_index_header() {
  local dest="$1"
  cat > "${dest}" <<'INDEX'
name|tar_name|load_ref|default_target_ref|platform|pull|dockerfile
INDEX
}

image_rows_for_arch() {
  local arch="$1"
  ENVOY_GATEWAY_VERSION="${ENVOY_GATEWAY_VERSION}" \
  ENVOY_PROXY_IMAGE="${ENVOY_PROXY_IMAGE}" \
  ENVOY_PROXY_TARGET="${ENVOY_PROXY_TARGET}" \
  python3 - "${ROOT_DIR}/images/image.json" "${arch}" <<'PY'
import json, os, sys
path, arch = sys.argv[1], sys.argv[2]
with open(path, 'r', encoding='utf-8') as f:
    images = json.load(f)

def expand(value):
    if value is None:
        return ''
    out = str(value)
    for key, val in os.environ.items():
        out = out.replace('${' + key + '}', val)
    return out

matched = [i for i in images if i.get('arch') == arch]
if not matched:
    raise SystemExit(f'no images found for arch {arch}')
seen = set()
for i in matched:
    row = {k: expand(v) for k, v in i.items()}
    for key in ['name', 'tar', 'tag', 'platform']:
        if not row.get(key):
            raise SystemExit(f'image entry missing {key}: {i}')
    if not (row.get('pull') or row.get('dockerfile')):
        raise SystemExit(f'image entry must define pull or dockerfile: {i}')
    if row['tar'] in seen:
        raise SystemExit(f'duplicate tar name: {row["tar"]}')
    seen.add(row['tar'])
    print('|'.join([
        row.get('name', ''),
        row.get('tar', ''),
        row.get('tag', ''),
        row.get('tag', ''),
        row.get('platform', ''),
        row.get('pull', ''),
        row.get('dockerfile', ''),
    ]))
PY
}

prepare_images() {
  local arch="$1" image_dir="$2" index_file="$3"
  local name tar_name load_ref default_target_ref platform pull dockerfile
  write_image_index_header "${index_file}"
  while IFS='|' read -r name tar_name load_ref default_target_ref platform pull dockerfile; do
    [[ -n "${name}" ]] || continue
    echo "${name}|${tar_name}|${load_ref}|${default_target_ref}|${platform}|${pull}|${dockerfile}" >> "${index_file}"
    if [[ "${SKIP_IMAGES}" == "1" ]]; then
      info "skip image packaging: ${name} (${platform})"
      continue
    fi
    if [[ -n "${pull}" ]]; then
      info "pulling ${pull} for ${platform}"
      docker pull --platform "${platform}" "${pull}"
      docker tag "${pull}" "${load_ref}"
    else
      die "dockerfile image entries are not used by this package yet: ${name}"
    fi
    info "saving ${load_ref} -> ${tar_name}"
    docker save "${load_ref}" -o "${image_dir}/${tar_name}"
  done < <(image_rows_for_arch "${arch}")
}

build_one() {
  local arch="$1" chart_asset="$2"
  local platform build_dir payload_dir payload_tar run_name run_path
  platform="$(platform_for_arch "${arch}")"
  build_dir="${BUILD_ROOT}/${PACKAGE_NAME}-${ENVOY_GATEWAY_VERSION}-${arch}"
  payload_dir="${build_dir}/payload"
  payload_tar="${build_dir}/payload.tar.gz"
  run_name="${PACKAGE_NAME}-${ENVOY_GATEWAY_VERSION}-${arch}.run"
  run_path="${DIST_DIR}/${run_name}"

  info "building ${run_name} (${platform})"
  rm -rf "${build_dir}"
  mkdir -p "${payload_dir}/charts" "${payload_dir}/images" "${payload_dir}/meta" "${DIST_DIR}"

  cp "${chart_asset}" "${payload_dir}/charts/gateway-helm.tgz"
  cp "${ROOT_DIR}/images/image.json" "${payload_dir}/images/image.json"
  prepare_images "${arch}" "${payload_dir}/images" "${payload_dir}/images/image-index.tsv"

  cat > "${payload_dir}/meta/package.env" <<META
PACKAGE_NAME=${PACKAGE_NAME}
ENVOY_GATEWAY_VERSION=${ENVOY_GATEWAY_VERSION}
ARCH=${arch}
PLATFORM=${platform}
PACKAGE_TYPE=envoy-gateway-helm-images
DEFAULT_REGISTRY=${DEFAULT_REGISTRY}
DEFAULT_GATEWAY_IMAGE=${DEFAULT_REGISTRY}/envoyproxy/gateway:${ENVOY_GATEWAY_VERSION}
DEFAULT_ENVOY_PROXY_IMAGE=${ENVOY_PROXY_TARGET}
CHART_REF=${CHART_REF}
BUILT_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
META

  (cd "${payload_dir}" && tar -czf "${payload_tar}" .)
  tar -tzf "${payload_tar}" >/dev/null
  cat "${ROOT_DIR}/install.sh" "${payload_tar}" > "${run_path}"
  chmod +x "${run_path}"
  (cd "${DIST_DIR}" && sha256sum "${run_name}" > "${run_name}.sha256")
  info "wrote ${run_path}"
  info "wrote ${run_path}.sha256"

  if [[ "${KEEP_BUILD}" != "1" ]]; then
    rm -rf "${build_dir}"
  fi
}

mkdir -p "${BUILD_ROOT}" "${DIST_DIR}"
CHART_ASSET="$(prepare_chart_asset)"
while read -r target_arch; do
  build_one "${target_arch}" "${CHART_ASSET}"
done < <(arch_list)

if [[ "${KEEP_BUILD}" != "1" ]]; then
  rm -rf "${BUILD_ROOT}/chart-${ENVOY_GATEWAY_VERSION}"
fi

info "artifacts:"
ls -lh "${DIST_DIR}"/*.run "${DIST_DIR}"/*.sha256
